site_name: FlexiCam Documentation
site_description: Camera Modes Plugin for Unreal Engine 5
site_author: egorkapk
site_url: https://github.com/egorkapk/flexicam-docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.images
    - search.highlight
    - search.suggest
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

plugins:
   - glightbox
   - mkdoxy:
      projects:
        ะก++API: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: Source # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - Examples: examples/overview.md
  - C++ API Reference: ะก++API/annotated.md